### ISSUE TITLE
TODO capa de persistencia

### ISSUE THREAD

**Issue by matisouza** [training-practice-sofkau/C1-2023--DDD-Uruguay#30]
- [ ] crear la carpeta environment y los archivos .env.prod .env.dev .env.test 

First TODO: persistence>database>mysql>
- [ ] config
- [ ] entities
- [ ] repositories, primero la base, luego los repositorios
- [ ] services
- [ ] en el modulo de my-sql declarar, importar y exportar

En persistence, queda entities y services.
- [ ] entities
- [ ] services
- [ ] revisar el modulo de persistence

**Comment by matisouza** [comment]
DB_HOST=localhost
DB_PORT=3306
DB_USER=su usuario
DB_PASSWORD=su contraseña
DB_NAME=nombre de la DB
