### ISSUE TITLE
TODO broker

### ISSUE THREAD

**Issue by matisouza** [training-practice-sofkau/C1-2023--DDD-Uruguay#40]
Podman antes que todo!

primero: dentro infraestructura en útil, creamos los comandos con validaciones

- [x]  commands

segundo:  dentro de la capa de menssaging, creamos el modulo y las 2 carpetas, publisher y subscribers

- [x] publisher
- [x] subscriber

tercero: dentro de publisher crear los eventos

- [x] eventos

tercero: crear la carpeta controller y crear los controladores.

- [x] controllers
- [x] los metodos post get put patch
- [x] levantar el caso de uso

cuarto: crear la carpeta subscriber

- [x] crear los subscriber 
- [x] agregar al main la información necesaria ( iniciar los microservicios )
